---
title: "Immune Analyses"
---

```{r message=FALSE, warning=FALSE, include=FALSE}
source("required.R")
tCells_allSamples <- readRDS("/projects/marralab/cayan_prj/PrecisionMed/Data/allTCells_merged_fastMNNCorrected.RDS")
```

# Analysis of the Immune Microenvironment

In total, there are `r ncol(tCells_allSamples)` T cells across `r length(unique(tCells_allSamples@meta.data[["ID"]]))` samples

```{r message=FALSE, warning=FALSE}
DimPlot(tCells_allSamples, reduction = "umap", group.by = "cellSubtype") +
  ggtitle("T-cell Subtype") +
  scale_color_nejm()
```

## Expression of Immune Checkpoint Markers

```{r message=FALSE, warning=FALSE, include=FALSE}
immuneMarkers <- c("PDCD1", "CD276", "HAVCR2", "LAG3", "TIGIT", "VSIR")

# function for plotting markers
plotICMarkers <- function(sample){
  tCells_sample <- subset(tCells_allSamples, ID == sample)
  expMat <- tCells_sample@assays[["RNA"]]@data[immuneMarkers,] %>%
    t() %>%
    as.data.frame() %>%
    rownames_to_column(var = "barcode")
  
  umapCoords <- tCells_sample@reductions[["umap"]]@cell.embeddings %>%
    as.data.frame() %>%
    rownames_to_column(var = "barcode")
  
  df <- inner_join(expMat, umapCoords, by = "barcode") %>%
    pivot_longer(cols = immuneMarkers, names_to = "Marker", values_to = "Expression")
  nonZero_df <- dplyr::filter(df, Expression > 0)
  
  plot <- df %>%
    ggplot(aes(x = UMAP_1, y = UMAP_2, colour = Expression)) +
    geom_point(alpha = 0.5) +
    geom_point(data = nonZero_df, aes(x = UMAP_1, y = UMAP_2, colour = Expression)) +
    facet_wrap(~Marker) +
    theme_classic() +
    scale_colour_gradient(low = "#CCCCCC", high = "#9C6AAA") +
    labs(x = "UMAP1", y = "UMAP2", colour = "Normalized\nExpression") +
    ggtitle(sample)
  print(plot)
}
```

```{r message=FALSE, warning=FALSE}
samples <- c("POG1128_2", "POG643_1", "POG643_2", "POG318", "POG326")
for(s in samples){
  plotICMarkers(s)
}
```




