---
title: "POG1128, Biopsy 1"
---

```{r message=FALSE, warning=FALSE, include=FALSE}
source("required.R")
f <- "POG1128_2"
seu <- readRDS(paste0(path, f, "/separate_ProcessedSeurat.RDS"))
```

# Phylogic Outputs

```{r}
phylOut <- fread(paste0(path, f, "/phylogicOut/", f, ".mut_ccfs.txt"))
phylOut_clusters <- fread(paste0(path, f, "/phylogicOut/", f, ".cluster_ccfs.txt"))

cellClusterEnrichment <- fread(paste0(path, f, "/phylogicCluster_cellEnrichment.csv"))
cellClusterEnrichment$barcode <- convert_atac_indices(gsub("\\.", "-", cellClusterEnrichment$barcode))
```

## Cluster validity

```{r}
# validClusters <- fread("/projects/marralab/cayan_prj/PrecisionMed/Data/pycloneClusters_snvDistr_tTestRes_randomAssigClusterSNVs.csv") %>%
#   dplyr::filter(sample == f) %>%
#   group_by(cluster) %>%
#   mutate(pAdj = p.adjust(pVal, method = "fdr")) %>%
#   summarize(snvProp = mean(snvProp),
#             medPAdj = median(pAdj),
#             meanPAdj = mean(pAdj))
# print(validClusters)
```

## Universal mutation cluster

```{r}
p1 <- DimPlot(seu, reduction = "rna.umap")

cluster_scores <- cellClusterEnrichment %>%
  column_to_rownames(var = "barcode")
seu <- AddMetaData(seu, cluster_scores)
p2 <- FeaturePlot(seu, reduction = "rna.umap", features = "cluster1") +
  ggtitle("Enrichment score for\ncluster of universal mutations")
print(plot_grid(p1, p2))
```

## Other clusters

```{r}
for(n in colnames(cluster_scores)){
  print(FeaturePlot(seu, reduction = "rna.umap", features = n) +
          ggtitle(n))
}
```


